/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyMina.vista.interfaces;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import proyMina.modelo.clsConnection;
import proyMina.modelo.clsFunciones;
import proyMina.modelo.clsGlobales;
import proyMina.modelo.clsOperacionesUsuarios;



/**
 *
 * @author josue
 */
public class FarmaciaInventario extends javax.swing.JFrame {
            DefaultTableModel model;        

    Date dateHoy = new Date();
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    clsConnection oConn = new clsConnection();
    clsFunciones oFunc = new clsFunciones();
    clsOperacionesUsuarios oPe = new clsOperacionesUsuarios();
    int idFarmacia=0;
    
    /**
     * Creates new form FirmaDigital
     */
    public FarmaciaInventario() {
        initComponents();
        jTableRecetas.setDefaultRenderer(Object.class, new ColorCelda());

        this.setLocationRelativeTo(null);
        AutoCompleteDecorator.decorate(this.jComboBoxSede);
        cargarSedes();
        cargarTablaFarmacia();
        jTextFieldHc.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cboEspecialidad = new javax.swing.JComboBox();
        jTextFieldHc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldNamesPaciente = new javax.swing.JTextField();
        jTextFieldEdadPaciente = new javax.swing.JTextField();
        jTextFieldDatosMedico = new javax.swing.JTextField();
        fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRecetas = new javax.swing.JTable();
        btnLimpiarCancelarTriaje = new javax.swing.JButton();
        BuscarPaciente1 = new javax.swing.JToggleButton();
        btnActualizar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFarmacia = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BuscarPaciente = new javax.swing.JToggleButton();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldNameProd = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jComboBoxSede = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldDescripcion = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fecha_vencimiento = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(FarmaciaInventario.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        cboEspecialidad.setEditable(true);
        cboEspecialidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboEspecialidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboEspecialidadPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboEspecialidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboEspecialidadMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboEspecialidadMousePressed(evt);
            }
        });
        cboEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEspecialidadActionPerformed(evt);
            }
        });
        cboEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboEspecialidadKeyPressed(evt);
            }
        });

        jTextFieldHc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHcActionPerformed(evt);
            }
        });

        jLabel19.setText("Especialidades:");

        jLabel20.setText("Historia Clinica:");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel21.setText("Nombres y Apellidos:");

        jLabel22.setText("Edad:");

        jLabel23.setText("Fecha del examen:");

        jLabel24.setText("Medico:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNamesPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDatosMedico)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextFieldEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldNamesPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jTextFieldEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldDatosMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTableRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableRecetas);

        btnLimpiarCancelarTriaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiarCancelarTriaje.setText("Limpiar");
        btnLimpiarCancelarTriaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCancelarTriajeActionPerformed(evt);
            }
        });

        BuscarPaciente1.setBackground(new java.awt.Color(222, 116, 17));
        BuscarPaciente1.setForeground(new java.awt.Color(243, 131, 5));
        BuscarPaciente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        BuscarPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPaciente1ActionPerformed(evt);
            }
        });

        btnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnActualizar1.setText("Actualizar");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldHc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(46, 46, 46)
                        .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BuscarPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(233, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarCancelarTriaje))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldHc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20))
                    .addComponent(BuscarPaciente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLimpiarCancelarTriaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ATENCION DE RECETAS", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jTableFarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableFarmaciaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFarmacia);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel17.setText("Producto:");

        BuscarPaciente.setBackground(new java.awt.Color(222, 116, 17));
        BuscarPaciente.setForeground(new java.awt.Color(243, 131, 5));
        BuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        BuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarPaciente)
                        .addGap(0, 471, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(BuscarPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agegar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lapiz.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel10.setText("Sede:");

        jLabel9.setText("Tipo : ");

        jLabel11.setText("Nombre Producto:");

        jLabel12.setText("Marca:");

        jComboBoxSede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));

        jLabel13.setText("Cantidad:");

        jTextFieldDescripcion.setColumns(20);
        jTextFieldDescripcion.setRows(5);
        jScrollPane2.setViewportView(jTextFieldDescripcion);

        jLabel14.setText("Descripcion:");

        jLabel15.setText("F. Vencimiento:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel16.setText("INVENTARIO DE FARMACIA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxSede, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNameProd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fecha_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(110, 110, 110)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldNameProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("INVENTARIO ", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void BuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPacienteActionPerformed
      
        

    }//GEN-LAST:event_BuscarPacienteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        btnRegistrar();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTableFarmaciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFarmaciaMousePressed
       if (evt.getClickCount() == 2) {
                //     System.out.println("va entrar en el cod de 2 click");
                //Integer cod = Integer.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 0).toString());
               // System.out.println("el cod es:" + cod);
                idFarmacia=Integer.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 0).toString());
                jComboBoxSede.setSelectedItem(String.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 1).toString()));
                jTextFieldTipo.setText(String.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 2).toString()));
                jTextFieldNameProd.setText(String.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 3).toString()));
                jTextFieldMarca.setText(String.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 6).toString()));
                jTextFieldCantidad.setText(String.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 4).toString()));
                jTextFieldDescripcion.setText(String.valueOf(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 5).toString()));
           try {
               fecha_vencimiento.setDate(formato.parse(jTableFarmacia.getValueAt(jTableFarmacia.getSelectedRow(), 7).toString()));
           } catch (ParseException ex) {
               Logger.getLogger(FarmaciaInventario.class.getName()).log(Level.SEVERE, null, ex);
           }
       
       }
    }//GEN-LAST:event_jTableFarmaciaMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     
       
    }//GEN-LAST:event_formWindowClosing

    private void cboEspecialidadPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboEspecialidadPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadPopupMenuWillBecomeInvisible

    private void cboEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadMouseClicked

    private void cboEspecialidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboEspecialidadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadMouseEntered

    private void cboEspecialidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboEspecialidadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadMousePressed

    private void cboEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadActionPerformed

    private void cboEspecialidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboEspecialidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadKeyPressed

    private void btnLimpiarCancelarTriajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCancelarTriajeActionPerformed
        
    }//GEN-LAST:event_btnLimpiarCancelarTriajeActionPerformed

    private void jTextFieldHcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHcActionPerformed
        cargarEspecialidades();
        cargarDatosPacienteHC();
    }//GEN-LAST:event_jTextFieldHcActionPerformed

    private void BuscarPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPaciente1ActionPerformed
        if(cboEspecialidad.getSelectedIndex()>0 && jTextFieldHc.getText().toString().trim().length()>0)
        llenar_tabla_hc();
    }//GEN-LAST:event_BuscarPaciente1ActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        
        actualizarRecetarioFarmacia();
        
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
             private void actualizarRecetarioFarmacia(){
            String strSqlStmt="";
            Integer cant_total=0,cantidad_despachada=0;
                 int a =jTableRecetas.getSelectedRow();
       System.out.println("la fila es:"+a);
            for(int i=0; i<jTableRecetas.getRowCount();i++)
            {
                cant_total=Integer.valueOf(String.valueOf(jTableRecetas.getValueAt(i, 3)));
                cantidad_despachada=Integer.valueOf(String.valueOf(jTableRecetas.getValueAt(i, 6)));
                       System.out.println("CANTIDADA DESPACHADA ES:"+cantidad_despachada);
                       System.out.println("CANTIDADA TOTAL ES:"+cant_total);

                if(cantidad_despachada<=cant_total)
                {
                    if(String.valueOf(jTableRecetas.getValueAt(i, 7)).trim().equals("SIN ATENDER"))
                    {
                    strSqlStmt="update desktop_medicamento_x_expecialidad_hc set cantidad_despachada_farmacia="
                    + String.valueOf(jTableRecetas.getValueAt(i, 6)).trim()+", estado_atendido_farmacia="+true+",fecha_registro_farmacia='"+
                    formato.format(dateHoy)+"',user_registro_farmacia='"+clsGlobales.sUser+"' "              
                    +"where id_medicamento_diag='"+String.valueOf(jTableRecetas.getValueAt(i, 0)).trim()+"'";
                    System.out.println(strSqlStmt);
                    }
                    else
                    {
                    strSqlStmt="update desktop_medicamento_x_expecialidad_hc set cantidad_despachada_farmacia="
                    + String.valueOf(jTableRecetas.getValueAt(i, 6)).trim()+",fecha_actualizacion_farmacia='"+
                    formato.format(dateHoy)+"',user_actualizacion_farmacia='"+clsGlobales.sUser+"' "            
                    +"where id_medicamento_diag='"+String.valueOf(jTableRecetas.getValueAt(i, 0)).trim()+"'";
                    System.out.println(strSqlStmt);
                    }
            if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt)){
               // oFunc.SubSistemaMensajeInformacion("Se ha actualizado con Éxito");
            }else{
                 //oFunc.SubSistemaMensajeError("Error en registro");
                 }
                }
                else
                    oFunc.SubSistemaMensajeError("La cantidad despacahada tiene que ser menor o igual al total recetado");
            
            }
                    llenar_tabla_hc();

      
    
}
        private void btnRegistrar(){
            if(!oPe.validarText(jTextFieldNameProd,"desktop_farmacia_inventario","nombre_sede")){
            if (Validar()){
                int key= oFunc.contadorPrimario("desktop_farmacia_inventario");
            String strSqlStmt;
            String Query ;
            strSqlStmt="INSERT INTO desktop_farmacia_inventario (";
            Query="Values(";
            strSqlStmt += "id_farmacia";Query +=key+",";
            strSqlStmt += ",nombre_sede";Query +="'"+jComboBoxSede.getSelectedItem().toString().trim()+"'";
            strSqlStmt += ",tipo";Query += ",'"+jTextFieldTipo.getText().toString().toUpperCase().trim()+ "'";
            strSqlStmt += ",nombre_producto";Query += ",'"+jTextFieldNameProd.getText().toString().toUpperCase().trim()+ "'";
            strSqlStmt += ",marca";Query += ",'"+jTextFieldMarca.getText().toString().toUpperCase().trim()+ "'";
            strSqlStmt += ",cantidad";Query += ","+jTextFieldCantidad.getText().toString().toUpperCase().trim()+ "";
            strSqlStmt += ",descripcion";Query += ",'"+jTextFieldDescripcion.getText().toString().toUpperCase().trim()+ "'";
            strSqlStmt += ",fecha_vencimiento";Query += ",'"+fecha_vencimiento.getDate()+"'";     
            strSqlStmt += ",user_registro";Query += ",'"+clsGlobales.sUser+ "'";
            strSqlStmt += ",fecha_registro";Query += ",'"+formato.format(dateHoy)+ "'";
            
            System.out.println("el comando es: " + strSqlStmt.concat(") ") + Query.concat(")")); 
            if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt.concat(") ") + Query.concat(")"))){
                oFunc.SubSistemaMensajeInformacion("Se ha registrado con Éxito");
                cargarTablaFarmacia();
            } else{
                    oFunc.SubSistemaMensajeError("No se pudo Registrar");
              
                       }         
            }        
        }   
            else                     
                oFunc.SubSistemaMensajeError("El Ruc ya se encuentra Registrado ");
    
    
    }
        
            private boolean Validar(){
                boolean bResultado=true;
                     if ( jTextFieldNameProd.getText().trim().length() >= 1 )
                        {
                        } else {  
                    oFunc.SubSistemaMensajeError("se debe de registrar el nombre del producto");
                                bResultado = false;
                                }
 
                              return bResultado;

            }
        
     private void cargarSedes(){
      String sQuery;        
        // Prepara el Query
        sQuery ="select nombre_sede from desktop_sede;";
        
        if (oConn.FnBoolQueryExecute(sQuery))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {                     
                     // Obtiene los datos de la Consulta
                     jComboBoxSede.addItem(oConn.setResult.getString ("nombre_sede").toUpperCase());
                    }
               
                 // Cierra Resultados
               
            } 
            catch (SQLException ex) 
            {
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensajeInformacion(ex.toString());
                Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            oConn.setResult.close();
            oConn.sqlStmt.close(); 

        } catch (SQLException ex) {
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
        // selecciona
        jComboBoxSede.setSelectedIndex(0);

}
     
         private void cargarTablaFarmacia(){
               
            try {
                model = new DefaultTableModel(){
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return false;
                    }};
                String vSql="select dfi.id_farmacia,dfi.nombre_sede,dfi.tipo,dfi.nombre_producto,dfi.cantidad as cantidad_total,\n" +
"	(CASE WHEN (select (case when cantidad1 is null then 0 else cantidad1 end) +\n" +
"		(case when cantidad2 is null then 0 else cantidad2 end) +\n" +
"		(case when cantidad3 is null then 0 else cantidad3 end) +\n" +
"		(case when cantidad4 is null then 0 else cantidad4 end)\n" +
"	from desktop_historia_clinica_detalle where (trata1 <> 'N/A' and trata2 <> 'N/A' and trata3 <> 'N/A' and trata4 <> 'N/A') or \n" +
"	trata1=dfi.nombre_producto or trata2=dfi.nombre_producto or trata3=dfi.nombre_producto or trata4=dfi.nombre_producto\n" +
"	) IS NULL THEN 0 ELSE \n" +
"	(select (case when cantidad1 is null then 0 else cantidad1 end) +\n" +
"		(case when cantidad2 is null then 0 else cantidad2 end) +\n" +
"		(case when cantidad3 is null then 0 else cantidad3 end) +\n" +
"		(case when cantidad4 is null then 0 else cantidad4 end)\n" +
"	from desktop_historia_clinica_detalle where (trata1 <> 'N/A' and trata2 <> 'N/A' and trata3 <> 'N/A' and trata4 <> 'N/A') or \n" +
"	trata1=dfi.nombre_producto or trata2=dfi.nombre_producto or trata3=dfi.nombre_producto or trata4=dfi.nombre_producto\n" +
"	)\n" +
"	END) as cantidad_consumida,\n" +
"	dfi.descripcion,dfi.marca,dfi.fecha_vencimiento \n" +
"	from desktop_farmacia_inventario AS dfi;";
    
                if (oConn.FnBoolQueryExecute(vSql))
                {
                    try  {
                        java.sql.ResultSetMetaData rsmt = oConn.setResult.getMetaData();
                        int CantidaColumnas = rsmt.getColumnCount();
                        for (int i = 1; i <= CantidaColumnas; i++) {
                            model.addColumn(rsmt.getColumnLabel(i));
                        }
                        while (oConn.setResult.next())
                        {
                            Object [] Fila = new Object[CantidaColumnas];
                            for (int i = 0; i < CantidaColumnas; i++) {
                                Fila[i] = oConn.setResult.getObject(i+1);
                            }
                            model.addRow(Fila);
                        }
                        jTableFarmacia.setModel(model);
                        oConn.setResult.close();
                    }
                    catch (SQLException ex)
                    {
                        oFunc.SubSistemaMensajeError(ex.toString());
                        Logger.getLogger(FarmaciaInventario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(FarmaciaInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
  
           private void cargarEspecialidades(){
      String sQuery;        
        // Prepara el Query
        sQuery ="select tipo from desktop_historia_clinica_detalle where n_orden="+jTextFieldHc.getText().toString().trim();
        if (oConn.FnBoolQueryExecute(sQuery)){
            try{
                // Verifica resultados
                while (oConn.setResult.next()){                     
                     // Obtiene los datos de la Consulta
                     cboEspecialidad.addItem(oConn.setResult.getString ("tipo").toUpperCase());
                }
            } 
            catch (SQLException ex){
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensajeInformacion(ex.toString());
            Logger.getLogger(FichaTriaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        cboEspecialidad.setSelectedIndex(0);
        }
}
         
                   private void cargarDatosPacienteHC(){
      String sQuery;        
        // Prepara el Query
        sQuery ="select  dat_pa.nombres || dat_pa.apellidos as nombres,dsk_hcd.fecha_registro as fecha_examen, \n" +
"		EXTRACT(YEAR FROM AGE(CURRENT_DATE, dat_pa.fecha_nacimiento)) AS edad, \n" +
"		desk_emp.nombres || desk_emp.apellidos as doctor\n" +
"	from desktop_historia_clinica_detalle as dsk_hcd \n" +
"	inner join desktop_datos_historia_clinica as desk_dhc on dsk_hcd.n_orden=desk_dhc.n_orden\n" +
"	inner join desktop_datos_pacientes as dat_pa on desk_dhc.dni_paciente=dat_pa.dni	\n" +
"	inner join desktop_empleado as desk_emp on desk_emp.name_user=desk_dhc.user_registro\n" +
"		where desk_dhc.n_orden="+jTextFieldHc.getText().toString().trim()+ " limit 1";
        System.out.println(sQuery);
        if (oConn.FnBoolQueryExecute(sQuery)){
            try{
                // Verifica resultados
                while (oConn.setResult.next()){                     
                     // Obtiene los datos de la Consulta
                     jTextFieldNamesPaciente.setText(oConn.setResult.getString ("nombres").toUpperCase());
                     jTextFieldEdadPaciente.setText(oConn.setResult.getString ("edad").toUpperCase());
                     fecha_nacimiento.setDate(oConn.setResult.getDate("fecha_examen"));
                     jTextFieldDatosMedico.setText(oConn.setResult.getString ("doctor").toUpperCase());
                }
            } 
            catch (SQLException ex){
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensajeInformacion(ex.toString());
            Logger.getLogger(FichaTriaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        cboEspecialidad.setSelectedIndex(0);
        }
}
         
private void llenar_tabla_hc(){
               
            try {
                model = new DefaultTableModel(){
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        if (columnIndex==6)
                            return true;
                        else
                        return false;
                    }};
                String vSql="select dskt_mxe.id_medicamento_diag as id_med, dcie.descripcion as cie10,dskt_fminv.nombre_producto as medicamento,\n" +
"		dskt_mxe.cantidad_total_recetado as cantidad,dskt_mxe.horas as horario,dskt_mxe.frecuencia_dias as dias,\n" +
"		dskt_mxe.cantidad_despachada_farmacia as cantidad_despachada, \n" +
"		(case when (dskt_mxe.estado_atendido_farmacia)=true then 'ATENDIDO' ELSE 'SIN ATENDER' END) AS estado\n" +
"		from desktop_datos_historia_clinica as hist_clini\n" +
"inner join desktop_historia_clinica_detalle as dskt_hcd on hist_clini.n_orden=	dskt_hcd.n_orden\n" +
"inner join desktop_diagnostico_x_expecialidad_hc as dskt_dxe on dskt_dxe.n_orden=hist_clini.n_orden\n" +
"inner join desktop_medicamento_x_expecialidad_hc as dskt_mxe on dskt_mxe.id_diag_x_espe_hc=dskt_dxe.id_diag_x_espe_hc\n" +
"inner join desktop_cie10 as dcie on  dskt_dxe.codigo_cie10=dcie.codigo\n" +
"inner join desktop_farmacia_inventario as dskt_fminv on dskt_fminv.id_farmacia=dskt_mxe.id_farmacia	"
 + "where dskt_hcd.n_orden="+jTextFieldHc.getText().toString().trim()+" and dskt_hcd.tipo='"+cboEspecialidad.getSelectedItem().toString().trim()+"'";
                
                if (oConn.FnBoolQueryExecute(vSql))
                {
                    try  {
                        java.sql.ResultSetMetaData rsmt = oConn.setResult.getMetaData();
                        int CantidaColumnas = rsmt.getColumnCount();
                        for (int i = 1; i <= CantidaColumnas; i++) {
                            model.addColumn(rsmt.getColumnLabel(i));
                        }
                        while (oConn.setResult.next())
                        {
                            Object [] Fila = new Object[CantidaColumnas];
                            for (int i = 0; i < CantidaColumnas; i++) {
                                Fila[i] = oConn.setResult.getObject(i+1);
                            }
                            model.addRow(Fila);
                        }
                        jTableRecetas.setModel(model);
                        ajustarTamañoTabla();
                        oConn.setResult.close();
                    }
                    catch (SQLException ex)
                    {
                        oFunc.SubSistemaMensajeError(ex.toString());
                        Logger.getLogger(FarmaciaInventario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(FarmaciaInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
         public void ajustarTamañoTabla(){
    jTableRecetas.getColumn("id_med").setMaxWidth(20); 
    jTableRecetas.getColumn("cie10").setMaxWidth(500);
        jTableRecetas.getColumn("medicamento").setMaxWidth(300);
    jTableRecetas.getColumn("cantidad").setMaxWidth(60); 
    jTableRecetas.getColumn("horario").setMaxWidth(60);
    jTableRecetas.getColumn("dias").setMaxWidth(60);
    jTableRecetas.getColumn("cantidad_despachada").setMaxWidth(180);
    jTableRecetas.getColumn("estado").setMaxWidth(100);
    }       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmaciaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BuscarPaciente;
    private javax.swing.JToggleButton BuscarPaciente1;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarCancelarTriaje;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cboEspecialidad;
    private com.toedter.calendar.JDateChooser fecha_nacimiento;
    private com.toedter.calendar.JDateChooser fecha_vencimiento;
    private javax.swing.JComboBox<String> jComboBoxSede;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFarmacia;
    private javax.swing.JTable jTableRecetas;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldDatosMedico;
    private javax.swing.JTextArea jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldEdadPaciente;
    private javax.swing.JTextField jTextFieldHc;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNameProd;
    private javax.swing.JTextField jTextFieldNamesPaciente;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
