/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyMina.vista.interfaces;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import proyMina.modelo.clsConnection;
import proyMina.modelo.clsFunciones;
import proyMina.modelo.clsGlobales;
import proyMina.modelo.clsOperacionesUsuarios;

/**
 *
 * @author josue
 */
public class HistoriaClinicaGeriatria extends javax.swing.JFrame {
    Date dateHoy = new Date();
    SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
    clsConnection oConn = new clsConnection();
    clsFunciones oFunc = new clsFunciones();
    clsOperacionesUsuarios oPe = new clsOperacionesUsuarios();
    DefaultTableModel model;   
    /**
     * Creates new form HistoriaClinicaGeriatria
     */
    public HistoriaClinicaGeriatria() {
        initComponents();
        AutoCompleteDecorator.decorate(this.cboDiagnostico1);
        AutoCompleteDecorator.decorate(this.cboDiagnostico2);
        AutoCompleteDecorator.decorate(this.cboDiagnostico3);
        AutoCompleteDecorator.decorate(this.cboDiagnostico4);
        AutoCompleteDecorator.decorate(this.cboCodigo1);
        AutoCompleteDecorator.decorate(this.cboCodigo2);
        AutoCompleteDecorator.decorate(this.cboCodigo3);
        AutoCompleteDecorator.decorate(this.cboCodigo4);
        AutoCompleteDecorator.decorate(this.cboMedicamento1);
        AutoCompleteDecorator.decorate(this.cboMedicamento2);
        AutoCompleteDecorator.decorate(this.cboMedicamento3);
        AutoCompleteDecorator.decorate(this.cboMedicamento4);
       cargarMedicamentos();
        cargarDiagnosticos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        n_orden_hc = new javax.swing.JTextField();
        BuscarPaciente = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        nombres_hcpaciente = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextRecom = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextExamFisico = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cboCodigo1 = new javax.swing.JComboBox();
        cboDiagnostico1 = new javax.swing.JComboBox();
        cboDiagnostico2 = new javax.swing.JComboBox();
        cboCodigo2 = new javax.swing.JComboBox();
        cboDiagnostico3 = new javax.swing.JComboBox();
        cboCodigo3 = new javax.swing.JComboBox();
        cboDiagnostico4 = new javax.swing.JComboBox();
        cboCodigo4 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        cboMedicamento1 = new javax.swing.JComboBox();
        jTextFieldCantidad1 = new javax.swing.JTextField();
        jTextFieldHorario1 = new javax.swing.JTextField();
        jTextFieldFrecuencia1 = new javax.swing.JTextField();
        cboMedicamento2 = new javax.swing.JComboBox();
        jTextFieldCantidad2 = new javax.swing.JTextField();
        jTextFieldHorario2 = new javax.swing.JTextField();
        jTextFieldFrecuencia2 = new javax.swing.JTextField();
        cboMedicamento3 = new javax.swing.JComboBox();
        jTextFieldCantidad3 = new javax.swing.JTextField();
        jTextFieldHorario3 = new javax.swing.JTextField();
        jTextFieldFrecuencia3 = new javax.swing.JTextField();
        cboMedicamento4 = new javax.swing.JComboBox();
        jTextFieldCantidad4 = new javax.swing.JTextField();
        jTextFieldHorario4 = new javax.swing.JTextField();
        jTextFieldFrecuencia4 = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HISTORIA CLINICA GERIATRIA");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        n_orden_hc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_orden_hcActionPerformed(evt);
            }
        });
        n_orden_hc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n_orden_hcKeyTyped(evt);
            }
        });

        BuscarPaciente.setBackground(new java.awt.Color(222, 116, 17));
        BuscarPaciente.setForeground(new java.awt.Color(243, 131, 5));
        BuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        BuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPacienteActionPerformed(evt);
            }
        });

        jLabel23.setText("HISTORIA CLINICA:");

        nombres_hcpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombres_hcpacienteActionPerformed(evt);
            }
        });

        jLabel24.setText("NOMBRES Y APELLIDOS :");

        jLabel25.setText("EDAD :");

        jLabel26.setText("F. EVALUACION:");

        jLabel27.setText("AÑOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombres_hcpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n_orden_hc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(763, 763, 763))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(n_orden_hc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BuscarPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(nombres_hcpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTextRecom.setColumns(20);
        jTextRecom.setRows(5);
        jScrollPane1.setViewportView(jTextRecom);

        jLabel29.setText("Recomendaciones:");

        jTextExamFisico.setColumns(20);
        jTextExamFisico.setRows(5);
        jScrollPane2.setViewportView(jTextExamFisico);

        jLabel30.setText("Examen Fisico:");

        jTabbedPane5.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboCodigo1.setEditable(true);
        cboCodigo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboCodigo1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboCodigo1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboCodigo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCodigo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboCodigo1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboCodigo1MousePressed(evt);
            }
        });
        cboCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodigo1ActionPerformed(evt);
            }
        });
        cboCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboCodigo1KeyPressed(evt);
            }
        });

        cboDiagnostico1.setEditable(true);
        cboDiagnostico1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboDiagnostico1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboDiagnostico1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboDiagnostico1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDiagnostico1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboDiagnostico1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboDiagnostico1MousePressed(evt);
            }
        });
        cboDiagnostico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiagnostico1ActionPerformed(evt);
            }
        });
        cboDiagnostico1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDiagnostico1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboDiagnostico1KeyReleased(evt);
            }
        });

        cboDiagnostico2.setEditable(true);
        cboDiagnostico2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboDiagnostico2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboDiagnostico2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboDiagnostico2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDiagnostico2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboDiagnostico2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboDiagnostico2MousePressed(evt);
            }
        });
        cboDiagnostico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiagnostico2ActionPerformed(evt);
            }
        });
        cboDiagnostico2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDiagnostico2KeyPressed(evt);
            }
        });

        cboCodigo2.setEditable(true);
        cboCodigo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboCodigo2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboCodigo2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboCodigo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCodigo2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboCodigo2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboCodigo2MousePressed(evt);
            }
        });
        cboCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodigo2ActionPerformed(evt);
            }
        });
        cboCodigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboCodigo2KeyPressed(evt);
            }
        });

        cboDiagnostico3.setEditable(true);
        cboDiagnostico3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboDiagnostico3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboDiagnostico3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboDiagnostico3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDiagnostico3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboDiagnostico3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboDiagnostico3MousePressed(evt);
            }
        });
        cboDiagnostico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiagnostico3ActionPerformed(evt);
            }
        });
        cboDiagnostico3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDiagnostico3KeyPressed(evt);
            }
        });

        cboCodigo3.setEditable(true);
        cboCodigo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboCodigo3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboCodigo3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboCodigo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCodigo3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboCodigo3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboCodigo3MousePressed(evt);
            }
        });
        cboCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodigo3ActionPerformed(evt);
            }
        });
        cboCodigo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboCodigo3KeyPressed(evt);
            }
        });

        cboDiagnostico4.setEditable(true);
        cboDiagnostico4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboDiagnostico4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboDiagnostico4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboDiagnostico4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDiagnostico4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboDiagnostico4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboDiagnostico4MousePressed(evt);
            }
        });
        cboDiagnostico4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiagnostico4ActionPerformed(evt);
            }
        });
        cboDiagnostico4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDiagnostico4KeyPressed(evt);
            }
        });

        cboCodigo4.setEditable(true);
        cboCodigo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboCodigo4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboCodigo4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboCodigo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCodigo4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboCodigo4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboCodigo4MousePressed(evt);
            }
        });
        cboCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodigo4ActionPerformed(evt);
            }
        });
        cboCodigo4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboCodigo4KeyPressed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel40.setText("DIAGNOSTICOS");

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel41.setText("CODIGOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboDiagnostico3, 0, 740, Short.MAX_VALUE)
                    .addComponent(cboDiagnostico2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDiagnostico1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDiagnostico4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cboCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(94, 94, 94))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDiagnostico1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDiagnostico2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDiagnostico3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDiagnostico4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Diagnosticos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel43.setText("MEDICAMENTOS");

        jLabel44.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel44.setText("UNIDAD");

        jLabel45.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel45.setText("HORARIO");

        jLabel46.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel46.setText("FRECUENCIA");

        cboMedicamento1.setEditable(true);
        cboMedicamento1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboMedicamento1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMedicamento1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboMedicamento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMedicamento1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboMedicamento1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboMedicamento1MousePressed(evt);
            }
        });
        cboMedicamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicamento1ActionPerformed(evt);
            }
        });
        cboMedicamento1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboMedicamento1KeyPressed(evt);
            }
        });

        cboMedicamento2.setEditable(true);
        cboMedicamento2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboMedicamento2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMedicamento2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboMedicamento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMedicamento2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboMedicamento2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboMedicamento2MousePressed(evt);
            }
        });
        cboMedicamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicamento2ActionPerformed(evt);
            }
        });
        cboMedicamento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboMedicamento2KeyPressed(evt);
            }
        });

        cboMedicamento3.setEditable(true);
        cboMedicamento3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboMedicamento3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMedicamento3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboMedicamento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMedicamento3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboMedicamento3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboMedicamento3MousePressed(evt);
            }
        });
        cboMedicamento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicamento3ActionPerformed(evt);
            }
        });
        cboMedicamento3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboMedicamento3KeyPressed(evt);
            }
        });

        cboMedicamento4.setEditable(true);
        cboMedicamento4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        cboMedicamento4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMedicamento4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboMedicamento4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMedicamento4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboMedicamento4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboMedicamento4MousePressed(evt);
            }
        });
        cboMedicamento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicamento4ActionPerformed(evt);
            }
        });
        cboMedicamento4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboMedicamento4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addGap(167, 167, 167)
                .addComponent(jLabel45)
                .addGap(181, 181, 181)
                .addComponent(jLabel46)
                .addGap(95, 95, 95))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cboMedicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jTextFieldCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jTextFieldHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cboMedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jTextFieldCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jTextFieldHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cboMedicamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jTextFieldCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldHorario3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHorario4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cboMedicamento4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43)
                        .addComponent(jLabel44)
                        .addComponent(jLabel45)
                        .addComponent(jLabel46))
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMedicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMedicamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldHorario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMedicamento4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHorario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("TRATAMIENTO", jPanel3);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lapiz.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agegar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpiar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n_orden_hcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_orden_hcActionPerformed
   
    }//GEN-LAST:event_n_orden_hcActionPerformed

    private void n_orden_hcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_orden_hcKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        if (!numeros)
        {
            evt.consume();
        }
        if(n_orden_hc.getText().length()>=8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_n_orden_hcKeyTyped

    private void BuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPacienteActionPerformed

        cargarDatosPaciente();
    }//GEN-LAST:event_BuscarPacienteActionPerformed

    private void nombres_hcpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombres_hcpacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombres_hcpacienteActionPerformed

    private void cboCodigo4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboCodigo4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo4KeyPressed

    private void cboCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodigo4ActionPerformed
                if(cboCodigo4.getSelectedIndex()>0)        
        cargarDiagnosticosDescripcion(4);
    }//GEN-LAST:event_cboCodigo4ActionPerformed

    private void cboCodigo4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo4MousePressed

    private void cboCodigo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo4MouseEntered

    private void cboCodigo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo4MouseClicked

    private void cboCodigo4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboCodigo4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo4PopupMenuWillBecomeInvisible

    private void cboDiagnostico4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDiagnostico4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico4KeyPressed

    private void cboDiagnostico4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiagnostico4ActionPerformed
  
    }//GEN-LAST:event_cboDiagnostico4ActionPerformed

    private void cboDiagnostico4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico4MousePressed

    private void cboDiagnostico4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico4MouseEntered

    private void cboDiagnostico4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico4MouseClicked

    private void cboDiagnostico4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboDiagnostico4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico4PopupMenuWillBecomeInvisible

    private void cboCodigo3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboCodigo3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo3KeyPressed

    private void cboCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodigo3ActionPerformed
                if(cboCodigo3.getSelectedIndex()>0)       
        cargarDiagnosticosDescripcion(3);

    }//GEN-LAST:event_cboCodigo3ActionPerformed

    private void cboCodigo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo3MousePressed

    private void cboCodigo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo3MouseEntered

    private void cboCodigo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo3MouseClicked

    private void cboCodigo3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboCodigo3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo3PopupMenuWillBecomeInvisible

    private void cboDiagnostico3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDiagnostico3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico3KeyPressed

    private void cboDiagnostico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiagnostico3ActionPerformed

    }//GEN-LAST:event_cboDiagnostico3ActionPerformed

    private void cboDiagnostico3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico3MousePressed

    private void cboDiagnostico3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico3MouseEntered

    private void cboDiagnostico3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico3MouseClicked

    private void cboDiagnostico3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboDiagnostico3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico3PopupMenuWillBecomeInvisible

    private void cboCodigo2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboCodigo2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo2KeyPressed

    private void cboCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodigo2ActionPerformed
                if(cboCodigo2.getSelectedIndex()>0)       
        cargarDiagnosticosDescripcion(2);
    }//GEN-LAST:event_cboCodigo2ActionPerformed

    private void cboCodigo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo2MousePressed

    private void cboCodigo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo2MouseEntered

    private void cboCodigo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo2MouseClicked

    private void cboCodigo2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboCodigo2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo2PopupMenuWillBecomeInvisible

    private void cboDiagnostico2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDiagnostico2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico2KeyPressed

    private void cboDiagnostico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiagnostico2ActionPerformed

    }//GEN-LAST:event_cboDiagnostico2ActionPerformed

    private void cboDiagnostico2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico2MousePressed

    private void cboDiagnostico2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico2MouseEntered

    private void cboDiagnostico2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico2MouseClicked

    private void cboDiagnostico2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboDiagnostico2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico2PopupMenuWillBecomeInvisible

    private void cboDiagnostico1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDiagnostico1KeyPressed
               System.out.println("llego al key released");
           char c = (char) evt.getKeyCode();
    if(c == evt.VK_ENTER){
                System.out.println("esta en el enter");
                cargarDiagnosticosCodigo(1);
    }
        
    }//GEN-LAST:event_cboDiagnostico1KeyPressed

    private void cboDiagnostico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiagnostico1ActionPerformed

    }//GEN-LAST:event_cboDiagnostico1ActionPerformed

    private void cboDiagnostico1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico1MousePressed

    private void cboDiagnostico1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico1MouseEntered

    private void cboDiagnostico1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDiagnostico1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico1MouseClicked

    private void cboDiagnostico1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboDiagnostico1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiagnostico1PopupMenuWillBecomeInvisible

    private void cboCodigo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboCodigo1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo1KeyPressed

    private void cboCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodigo1ActionPerformed
                if(cboCodigo1.getSelectedIndex()>0)
        cargarDiagnosticosDescripcion(1);
    }//GEN-LAST:event_cboCodigo1ActionPerformed

    private void cboCodigo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo1MousePressed
        System.out.println("mouse presed");
    }//GEN-LAST:event_cboCodigo1MousePressed

    private void cboCodigo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo1MouseEntered

    private void cboCodigo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCodigo1MouseClicked

    }//GEN-LAST:event_cboCodigo1MouseClicked

    private void cboCodigo1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboCodigo1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodigo1PopupMenuWillBecomeInvisible

    private void cboMedicamento1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMedicamento1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento1PopupMenuWillBecomeInvisible

    private void cboMedicamento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento1MouseClicked

    private void cboMedicamento1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento1MouseEntered

    private void cboMedicamento1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento1MousePressed

    private void cboMedicamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento1ActionPerformed

    private void cboMedicamento1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMedicamento1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento1KeyPressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    registrarHistoria();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cboMedicamento2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMedicamento2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento2PopupMenuWillBecomeInvisible

    private void cboMedicamento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento2MouseClicked

    private void cboMedicamento2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento2MouseEntered

    private void cboMedicamento2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento2MousePressed

    private void cboMedicamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicamento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento2ActionPerformed

    private void cboMedicamento2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMedicamento2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento2KeyPressed

    private void cboMedicamento3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMedicamento3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento3PopupMenuWillBecomeInvisible

    private void cboMedicamento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento3MouseClicked

    private void cboMedicamento3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento3MouseEntered

    private void cboMedicamento3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento3MousePressed

    private void cboMedicamento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicamento3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento3ActionPerformed

    private void cboMedicamento3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMedicamento3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento3KeyPressed

    private void cboMedicamento4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMedicamento4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento4PopupMenuWillBecomeInvisible

    private void cboMedicamento4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento4MouseClicked

    private void cboMedicamento4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento4MouseEntered

    private void cboMedicamento4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicamento4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento4MousePressed

    private void cboMedicamento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicamento4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento4ActionPerformed

    private void cboMedicamento4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMedicamento4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicamento4KeyPressed

    private void cboDiagnostico1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDiagnostico1KeyReleased


    }//GEN-LAST:event_cboDiagnostico1KeyReleased

                private void cargarMedicamentos(){
            try {
                String sQuery;
                // Prepara el Query
                sQuery ="select nombre_producto from desktop_farmacia_inventario;";
                System.out.println(sQuery);
                if (oConn.FnBoolQueryExecute(sQuery))
                {
                    try
                    {
                        // Verifica resultados
                        while (oConn.setResult.next())
                        {
        
                                cboMedicamento1.addItem(oConn.setResult.getString ("nombre_producto"));
                                cboMedicamento2.addItem(oConn.setResult.getString ("nombre_producto"));
                                cboMedicamento3.addItem(oConn.setResult.getString ("nombre_producto"));
                                cboMedicamento4.addItem(oConn.setResult.getString ("nombre_producto"));
                           
                        }
                        
                        // Cierra Resultados
                        oConn.setResult.close();
                    }
                    catch (SQLException ex)
                    {
                        //JOptionPane.showMessageDialorootPane,ex);
                        oFunc.SubSistemaMensajeInformacion(ex.toString());
                        Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                // selecciona
                    cboMedicamento1.setSelectedIndex(0);
                    cboMedicamento2.setSelectedIndex(0);
                    cboMedicamento3.setSelectedIndex(0);
                    cboMedicamento4.setSelectedIndex(0);
      
                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
}
            private void cargarDiagnosticos(){
            try {
                String sQuery;
                // Prepara el Query
                sQuery ="select codigo,descripcion from desktop_cie10;";
                System.out.println(sQuery);
                if (oConn.FnBoolQueryExecute(sQuery))
                {
                    try
                    {
                        // Verifica resultados
                        while (oConn.setResult.next())
                        {
        
                                cboDiagnostico1.addItem(oConn.setResult.getString ("descripcion"));
                                cboCodigo1.addItem(oConn.setResult.getString ("codigo"));
                                cboDiagnostico2.addItem(oConn.setResult.getString ("descripcion"));
                                cboCodigo2.addItem(oConn.setResult.getString ("codigo"));                                
                                cboDiagnostico3.addItem(oConn.setResult.getString ("descripcion"));
                                cboCodigo3.addItem(oConn.setResult.getString ("codigo"));                                
                                cboDiagnostico4.addItem(oConn.setResult.getString ("descripcion"));
                                cboCodigo4.addItem(oConn.setResult.getString ("codigo"));                            
                        }
                        
                        // Cierra Resultados
                        oConn.setResult.close();
                    }
                    catch (SQLException ex)
                    {
                        //JOptionPane.showMessageDialorootPane,ex);
                        oFunc.SubSistemaMensajeInformacion(ex.toString());
                        Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                // selecciona
                    cboDiagnostico1.setSelectedIndex(0);
                    cboCodigo1.setSelectedIndex(0);
                    cboDiagnostico2.setSelectedIndex(0);
                    cboCodigo2.setSelectedIndex(0);
                    cboDiagnostico3.setSelectedIndex(0);
                    cboCodigo3.setSelectedIndex(0);
                    cboDiagnostico4.setSelectedIndex(0);
                    cboCodigo4.setSelectedIndex(0);
                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    
        
            private void cargarDiagnosticosDescripcion(int nivel){
            try {
                String sQuery="";
                // Prepara el Query
                if(nivel ==1)
                sQuery ="select descripcion from desktop_cie10 where codigo='"+cboCodigo1.getSelectedItem().toString().trim()+"'";
                if(nivel ==2)
                sQuery ="select descripcion from desktop_cie10 where codigo='"+cboCodigo2.getSelectedItem().toString().trim()+"'";
                if(nivel ==3)
                sQuery ="select descripcion from desktop_cie10 where codigo='"+cboCodigo3.getSelectedItem().toString().trim()+"'";
                if(nivel ==4)
                sQuery ="select descripcion from desktop_cie10 where codigo='"+cboCodigo4.getSelectedItem().toString().trim()+"'";                
                                                
                if (oConn.FnBoolQueryExecute(sQuery))
                {
                    try
                    {
                        // Verifica resultados
                         while (oConn.setResult.next())
                        {
                                if(nivel ==1)
                                cboDiagnostico1.setSelectedItem(oConn.setResult.getString ("descripcion"));
                                if(nivel ==2)
                                cboDiagnostico2.setSelectedItem(oConn.setResult.getString ("descripcion"));
                                if(nivel ==3)
                                cboDiagnostico3.setSelectedItem(oConn.setResult.getString ("descripcion"));
                                if(nivel ==4)
                                cboDiagnostico4.setSelectedItem(oConn.setResult.getString ("descripcion"));
                        }
                        
                        // Cierra Resultados
                        oConn.setResult.close();
                    }
                    catch (SQLException ex)
                    {
                        //JOptionPane.showMessageDialorootPane,ex);
                        oFunc.SubSistemaMensajeInformacion(ex.toString());
                        Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                // selecciona

                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
}
   
            
         private void cargarDiagnosticosCodigo(int nivel){
            try {
                String sQuery="";
                // Prepara el Query
                if(nivel ==1)
                sQuery ="select codigo from desktop_cie10 where descripcion='"+cboDiagnostico1.getSelectedItem().toString().trim()+"'";
                if(nivel ==2)
                sQuery ="select codigo from desktop_cie10 where descripcion='"+cboDiagnostico2.getSelectedItem().toString().trim()+"'";
                if(nivel ==3)
                sQuery ="select codigo from desktop_cie10 where descripcion='"+cboDiagnostico3.getSelectedItem().toString().trim()+"'";
                if(nivel ==4)
                sQuery ="select codigo from desktop_cie10 where descripcion='"+cboDiagnostico4.getSelectedItem().toString().trim()+"'";
                
                System.out.println(sQuery);
                if (oConn.FnBoolQueryExecute(sQuery))
                {
                    try
                    {
                        // Verifica resultados
                        while (oConn.setResult.next())
                        {
                                if(nivel ==1)
                                cboCodigo1.setSelectedItem(oConn.setResult.getString ("codigo"));
                                if(nivel ==2)
                                cboCodigo2.setSelectedItem(oConn.setResult.getString ("codigo"));
                                if(nivel ==3)
                                cboCodigo3.setSelectedItem(oConn.setResult.getString ("codigo"));
                                if(nivel ==4)
                                cboCodigo4.setSelectedItem(oConn.setResult.getString ("codigo"));
                        }
                        
                        // Cierra Resultados
                        oConn.setResult.close();
                    }
                    catch (SQLException ex)
                    {
                        //JOptionPane.showMessageDialorootPane,ex);
                        oFunc.SubSistemaMensajeInformacion(ex.toString());
                        Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                // selecciona

                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    
    private void cargarDatosPaciente(){
      String sQuery;     
      if(!n_orden_hc.getText().isEmpty()){


        // Prepara el Query
        sQuery ="select CONCAT(dtp.nombres,' ',dtp.apellidos) as nombres,\n" +
"	 EXTRACT(YEAR FROM age(current_date,dtp.fecha_nacimiento)) AS  edad, ddhc.fecha_registro as fecha_evaluacion\n" +
"	from desktop_datos_pacientes as dtp inner join desktop_datos_historia_clinica as ddhc\n" +
"	on dtp.dni=ddhc.dni_paciente where ddhc.n_orden="+n_orden_hc.getText().trim();
        if (oConn.FnBoolQueryExecute(sQuery))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {                     
                     // Obtiene los datos de la Consulta
                     nombres_hcpaciente.setText(oConn.setResult.getString ("nombres").toUpperCase());
                     edad.setText(oConn.setResult.getString ("edad").toUpperCase());
                     fecha_nacimiento.setDate(oConn.setResult.getDate("fecha_evaluacion"));
                 }
                 
                 // Cierra Resultados
               
            } 
            catch (SQLException ex) 
            {
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensajeInformacion(ex.toString());
                Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            oConn.setResult.close();
            oConn.sqlStmt.close(); 

        } catch (SQLException ex) {
            Logger.getLogger(HistoriaClinicaGeriatria.class.getName()).log(Level.SEVERE, null, ex);
        }
        // selecciona
      }
      else
                          oFunc.SubSistemaMensajeInformacion("Debe de ingresar una historia clinica");

}
    
    
    private void registrarHistoria(){
                String strSqlStmt;
            String Query ;
            strSqlStmt="INSERT INTO desktop_historia_clinica_detalle (";
            Query="Values(";
            strSqlStmt += "n_orden";Query += n_orden_hc.getText();
            strSqlStmt += ",tipo";Query += ",'GERIATRIA'";
            
            if(jTextExamFisico.getText().toString().trim().length()>0){
            strSqlStmt += ",examen_fisico";Query += ",'"+jTextExamFisico.getText().toString().toUpperCase().trim()+ "'";}
            else{
            strSqlStmt += ",examen_fisico";Query += ","+null;}

            if(jTextRecom.getText().toString().trim().length()>0){            
            strSqlStmt += ",recomendacion";Query += ",'"+jTextRecom.getText().toString().trim()+ "'";
            }
            else{
            strSqlStmt += ",recomendacion";Query += ","+null;}
                
            strSqlStmt += ",diagnostico1";Query += ",'"+cboDiagnostico1.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",codigo_diag1";Query += ",'"+cboCodigo1.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",diagnostico2";Query += ",'"+cboDiagnostico2.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",codigo_diag2";Query += ",'"+cboCodigo2.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",diagnostico3";Query += ",'"+cboDiagnostico3.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",codigo_diag3";Query += ",'"+cboCodigo3.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",diagnostico4";Query += ",'"+cboDiagnostico4.getSelectedItem().toString().trim()+ "'";
            strSqlStmt += ",codigo_diag4";Query += ",'"+cboCodigo4.getSelectedItem().toString().trim()+ "'";

            strSqlStmt += ",trata1";Query += ",'"+cboMedicamento1.getSelectedItem().toString().trim()+ "'";
            if(jTextFieldCantidad1.getText().toString().trim().length()>0){
            strSqlStmt += ",cantidad1";Query += ","+jTextFieldCantidad1.getText().toString().trim();}
            else{
            strSqlStmt += ",cantidad1";Query += ","+null;}    
            
            if(jTextFieldHorario1.getText().toString().trim().length()>0){
            strSqlStmt += ",horario1";Query += ",'"+jTextFieldHorario1.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",horario1";Query += ","+null;}   
            
            if(jTextFieldFrecuencia1.getText().toString().trim().length()>0){
            strSqlStmt += ",frecuencia1";Query += ",'"+jTextFieldFrecuencia1.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",frecuencia1";Query += ","+null;}   
            
            
            
            strSqlStmt += ",trata2";Query += ",'"+cboMedicamento2.getSelectedItem().toString().trim()+ "'";
            if(jTextFieldCantidad2.getText().toString().trim().length()>0){
            strSqlStmt += ",cantidad2";Query += ","+jTextFieldCantidad2.getText().toString().trim();}
            else{
            strSqlStmt += ",cantidad2";Query += ","+null;}    
            
            if(jTextFieldHorario2.getText().toString().trim().length()>0){
            strSqlStmt += ",horario2";Query += ",'"+jTextFieldHorario2.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",horario2";Query += ","+null;}   
            
            if(jTextFieldFrecuencia2.getText().toString().trim().length()>0){
            strSqlStmt += ",frecuencia2";Query += ",'"+jTextFieldFrecuencia2.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",frecuencia2";Query += ","+null;}              
            
            strSqlStmt += ",trata3";Query += ",'"+cboMedicamento3.getSelectedItem().toString().trim()+ "'";
            if(jTextFieldCantidad3.getText().toString().trim().length()>0){
            strSqlStmt += ",cantidad3";Query += ","+jTextFieldCantidad3.getText().toString().trim();}
            else{
            strSqlStmt += ",cantidad3";Query += ","+null;}    
            
            if(jTextFieldHorario3.getText().toString().trim().length()>0){
            strSqlStmt += ",horario3";Query += ",'"+jTextFieldHorario3.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",horario3";Query += ","+null;}   
            
            if(jTextFieldFrecuencia3.getText().toString().trim().length()>0){
            strSqlStmt += ",frecuencia3";Query += ",'"+jTextFieldFrecuencia3.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",frecuencia3";Query += ","+null;}
            
            strSqlStmt += ",trata4";Query += ",'"+cboMedicamento4.getSelectedItem().toString().trim()+ "'";
            if(jTextFieldCantidad4.getText().toString().trim().length()>0){
            strSqlStmt += ",cantidad4";Query += ","+jTextFieldCantidad4.getText().toString().trim();}
            else{
            strSqlStmt += ",cantidad4";Query += ","+null;}    
            
            if(jTextFieldHorario4.getText().toString().trim().length()>0){
            strSqlStmt += ",horario4";Query += ",'"+jTextFieldHorario4.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",horario4";Query += ","+null;}   
            
            if(jTextFieldFrecuencia4.getText().toString().trim().length()>0){
            strSqlStmt += ",frecuencia4";Query += ",'"+jTextFieldFrecuencia4.getText().toString().trim()+ "'";}
            else{
            strSqlStmt += ",frecuencia4";Query += ","+null;}   

            strSqlStmt += ",user_registro";Query += ",'"+clsGlobales.sUser+ "'";
            strSqlStmt += ",fecha_registro";Query += ",'"+formato.format(dateHoy)+ "'";
            System.out.println("el comando es: " + strSqlStmt.concat(") ") + Query.concat(")")); 
            if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt.concat(") ") + Query.concat(")"))){
                oFunc.SubSistemaMensajeInformacion("Se ha registrado el empleado con Éxito");
            } else{
                    oFunc.SubSistemaMensajeError("No se pudo registrar La Entrada");
                    btnEditar.setEnabled(false);
                    btnActualizar.setEnabled(false);
                    
                    }  
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaGeriatria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaGeriatria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaGeriatria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaGeriatria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriaClinicaGeriatria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BuscarPaciente;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cboCodigo1;
    private javax.swing.JComboBox cboCodigo2;
    private javax.swing.JComboBox cboCodigo3;
    private javax.swing.JComboBox cboCodigo4;
    private javax.swing.JComboBox cboDiagnostico1;
    private javax.swing.JComboBox cboDiagnostico2;
    private javax.swing.JComboBox cboDiagnostico3;
    private javax.swing.JComboBox cboDiagnostico4;
    private javax.swing.JComboBox cboMedicamento1;
    private javax.swing.JComboBox cboMedicamento2;
    private javax.swing.JComboBox cboMedicamento3;
    private javax.swing.JComboBox cboMedicamento4;
    private javax.swing.JTextField edad;
    private com.toedter.calendar.JDateChooser fecha_nacimiento;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextExamFisico;
    private javax.swing.JTextField jTextFieldCantidad1;
    private javax.swing.JTextField jTextFieldCantidad2;
    private javax.swing.JTextField jTextFieldCantidad3;
    private javax.swing.JTextField jTextFieldCantidad4;
    private javax.swing.JTextField jTextFieldFrecuencia1;
    private javax.swing.JTextField jTextFieldFrecuencia2;
    private javax.swing.JTextField jTextFieldFrecuencia3;
    private javax.swing.JTextField jTextFieldFrecuencia4;
    private javax.swing.JTextField jTextFieldHorario1;
    private javax.swing.JTextField jTextFieldHorario2;
    private javax.swing.JTextField jTextFieldHorario3;
    private javax.swing.JTextField jTextFieldHorario4;
    private javax.swing.JTextArea jTextRecom;
    private javax.swing.JTextField n_orden_hc;
    private javax.swing.JTextField nombres_hcpaciente;
    // End of variables declaration//GEN-END:variables
}
